python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_unet2/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "gatedaxialunet" --learning_rate 0.001 --imgsize 256 --gray "yes"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_medt2/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "MedT" --learning_rate 0.0001 --imgsize 256 --gray "no"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_deeplab_resnet/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "deeplab_resnet" --learning_rate 0.001 --imgsize 256 --gray "no"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_deeplab_drn/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "deeplab_drn" --learning_rate 0.001 --imgsize 256 --gray "no"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_deeplab_xception/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "deeplab_xception" --learning_rate 0.001 --imgsize 256 --gray "no"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/original_unet/' --batch_size 2 --epoch 102 --save_freq 20 --modelname "ori_unet" --learning_rate 0.001 --imgsize 256 --gray "no"
#python train.py --train_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/train/" --val_dataset "/home/htihe/Data/Nervesegmentation/Rearrange/val/" --direc '/home/htihe/NerveSegmentation/Medical-Transformer-main/test_logo/' --batch_size 2 --epoch 100 --save_freq 20 --modelname "logo" --learning_rate 0.0001 --imgsize 256 --gray "no"


